# In .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/python:3.12

WORKDIR /workspaces/rsvp-priority

# Change this line
COPY requirements.txt .

RUN pip install --user -r requirements.txt